language: python
sudo: false
cache:
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
    - $YT_DIR
    - $YTREE_DATA
  pip: true

addons:
  apt:
    packages:
      - graphviz

env:
  global:
    YT_DIR=$HOME/yt-git
    YTREE_DATA=$HOME/ytree_test

before_install:
  - |
    export PATH=/usr/lib/ccache:$PATH
    # configure ytree
    mkdir -p $HOME/.config/ytree
    echo "[ytree]" > $HOME/.config/ytree/ytreerc
    echo "test_data_dir = $YTREE_DATA" >> $HOME/.config/ytree/ytreerc

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    pip install --upgrade pip
    pip install --upgrade wheel
    pip install --upgrade setuptools
    pip install girder-client
    # install yt-dev
    if [ $YTDEV = 1 ]; then
      pip install cython
      if [ ! -f $YT_DIR/README.md ]; then
        git clone --branch=master https://github.com/yt-project/yt $YT_DIR
      fi
      pushd $YT_DIR
      git pull origin master
      git checkout master
      pip install -e .
      popd
    fi
    # install ytree
    pip install -e .[dev]

before_script:
  - |
    # download test data
    if [ ! -d $YTREE_DATA/rockstar ]; then
        girder-cli --api-url https://girder.hub.yt/api/v1 download 59835a1ee2a67400016a2cda $YTREE_DATA
    fi

script: pytest --cov=ytree tests

jobs:
  include:
    - stage: tests
      name: "tests with Python 2.7"
      python: 2.7

    - stage: tests
      name: "tests with Python 3.5"
      python: 3.5

    - stage: tests
      name: "tests with Python 3.6"
      python: 3.6
      after_success: coveralls

    - stage: tests
      name: "tests with yt-dev"
      python: 3.6
      env: YTDEV=1

    - stage: docs
      name: "docs build test"
      python: 3.6
      before_script: skip
      before_install: skip
      script:
        - |
          cd doc/source
          python -m sphinx -M html "." "_build" -W

    - stage: deploy
      name: "deploy to pypi"
      if: (tag =~ ^ytree) AND (branch = master)
      python: 3.6
      before_script: skip
      before_install: skip
      script: skip
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel --universal
        user: brittonsmith
        password:
          secure: sUj8IKNaYbFKjzTRe04Jnho9ayXjzelRHxlWQIIQPTC80qUzpDBWk5gdDASUMEb9q+MdP7M3CW0tkrzNHtAq6vLfOI0j533aO6iB3gXgubtqTNOCfuskuKXe7NLaQ3zSCtNA1JgQNRR6UxxehjV2namYHv6kSWWwETFF5omdPqVmunByFlYxRPORhJERyFhAT090zOTfggxCj6nH1okv1SBK7z4DLOP80K+0dgJBa/vRod7bchtJjWczv4shmr712ltaIgKUxNFy027yEMocte2CdZ/zKACxaG5j6pYAo30oTc72aUS/cYa0J5s6jITwZ6cNS6THfyON0POD9eu6a8GXBi57x4xHyb1tR0ZQkcMDgt8bdQ6XaCcp96oxC6QqjmParsDp0dXDHyw6A1SKBKzuGF0pMqvrTiFq2wEJTrc85Bd1eq30MERxIARjkYxnWg6jYW4Ns9BgMVmS567x2RzYEnHia4Ntr3kIyCxlxBmlm22jPj62ZyxhM5Bpbc1yE8J9M8NBnPCU2MvB5XoEnXLXt3X4Y41T9SjWaH/nyoFUp834ASoFgVDFNvGbui+dfBkudtJHtJvyzY0rhqihm/GoaL8WwtQyEbrm3cGGNpRWbl+U0qua3ffFsaaXZvqi+2knUqsdstig1EAocSCOF9cfQ2HDeP2f8zhRHPQvTAk=
        on:
          tags: true
          repo: brittonsmith/ytree
          os: linux
